[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/csn/*"
  to = "http://evtdb.csn.uchile.cl/:splat"
  status = 200
  force = true
